baseURL = "https://blog.bitshares.fun/"
DefaultContentLanguage = "zh" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "en-us"
title = "未完待续"
copyright = "This is a customized copyright."
theme = "diary"
# googleAnalytics = "UA-123-45"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "挖坑偶尔填"
enableGitalk = false
#livereId = "MTAyMC81Njg3OC8zMzM0Mg=="
enableReadingTime = true
favicon = "https://blog.bitshares.fun/favicon.ico"

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "My Blog" # will set 'og:site_name'
description = "My HomePage Description"  # will set 'og:description'

#[params.gitalk]
#  owner = "user"
#  repo = "repo name"
#  client_id = "your client id"
#  client_secret = "your client secret"
[taxonomies]
   tag = "tags"
   category = "categories"

[params.utterances]
repo="your repo"
term="[ENTER TERM HERE]"
label="your label"
theme="github-light"

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 3
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 4
[[menu.main]]
url = "/posts"
name = "Archive"
weight = 2
[[menu.main]]
url = "/tutorail/00.cover/"
name = "The craft of selfteaching"
weight = 5
[[menu.main]]
url = "/notes"
name = "Notes"
weight = 6
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 8
[[menu.main]]
url = "/luke"
name = "Luke's Special Column"
weight = 1
[[menu.main]]
url = "/bookshelf/bookshelf.html"
name = "BookShelf"
weight = 7
